### PR TITLE
Fix #43: Lowercase header names

### LINKED ISSUE #43: HTTP response headers should be converted to lowercase
Currently, we use code that depends on the `X-Cert-Pinning-Signature` HTTP header. However, some servers lowercase the values before they send the response, resulting in the `x-cert-pinning-signature` HTTP header which we later fail to check.

We should lowercase all response headers in the map and compare the lowercase headers.

### PR DESCRIPTION
**Pull request by hvge**

### CODE REVIEW

**Review by TomasKypta — APPROVED** [review]

File: library/src/main/java/com/wultra/android/sslpinning/CertStore.kt [hunk 1]
```diff
@@ -66,7 +66,7 @@ class CertStore internal constructor(private val configuration: CertStoreConfigu
                 .registerTypeAdapter(Date::class.java, DateTypeAdapter())
                 .create()
         internal const val REQUEST_CHALLENGE_HEADER = "X-Cert-Pinning-Challenge"
-        internal const val RESPONSE_SIGNATURE_HEADER = "X-Cert-Pinning-Signature"
+        internal const val RESPONSE_SIGNATURE_HEADER = "x-cert-pinning-signature"
```
Comment (TomasKypta) [inline library/src/main/java/com/wultra/android/sslpinning/CertStore.kt:69]: A comment why this one is lowercase might be nice.
